# Generated by Django 4.2.7 on 2023-11-28 11:31

import django.core.validators
from django.db import migrations, models
import helpers.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='market name')),
                ('cover_image', helpers.fields.ExtensionAwareImageField(upload_to='marketplace/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))])),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
