# Generated by Django 4.2.2 on 2023-11-28 11:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='cover_image',
            field=helpers.fields.ExtensionAwareImageField(upload_to='marketplace/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='store name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='store description')),
                ('logo', helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='store/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))])),
                ('cover_image', helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='store/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))])),
                ('country', models.CharField(max_length=255, verbose_name='country of location')),
                ('city', models.CharField(max_length=255, verbose_name='store city')),
                ('province', models.CharField(max_length=255, verbose_name='store province')),
                ('additional_information', models.JSONField(blank=True, null=True, verbose_name='store additional information')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='MarketPlace.marketplace')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='store vendor')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
