# Generated by Django 4.2.2 on 2023-11-28 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MarketPlace', '0002_alter_marketplace_cover_image_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='store name')),
                ('image', helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='products/category_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))])),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='cover_image',
            field=helpers.fields.ExtensionAwareImageField(upload_to='marketplace/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='store/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='store/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product description')),
                ('cover_image', helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='products/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif')), django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))])),
                ('quantity', models.IntegerField(default=0, verbose_name='available quantity')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='discount percentage')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='product selling price')),
                ('currency_symbol', models.CharField(default='₦', max_length=1, verbose_name='product currency symbol')),
                ('currency_abbrev', models.CharField(default='NGN', max_length=3, verbose_name='abbreviated product currency')),
                ('currency_verbose', models.CharField(default='Naira', max_length=20, verbose_name='verbose product currency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MarketPlace.productcategory')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MarketPlace.store')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
