# Generated by Django 4.2.2 on 2023-11-28 12:22

import django.core.validators
from django.db import migrations
import helpers.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0006_alter_marketplace_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='cover_image',
            field=helpers.fields.ExtensionAwareImageField(upload_to='marketplace/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='products/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='products/category_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=helpers.fields.ExtensionAwareImageField(upload_to='products/product_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))], verbose_name='image file'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='store/cover_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=helpers.fields.ExtensionAwareImageField(blank=True, null=True, upload_to='store/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'jfif'))]),
        ),
    ]
