# Generated by Django 4.2.2 on 2023-11-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0007_alter_marketplace_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='marketplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='MarketPlace.marketplace'),
            preserve_default=False,
        ),
    ]
