# Generated by Django 4.2.7 on 2023-11-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_at',
            new_name='updated_a',
        ),
    ]
