# Generated by Django 4.2.7 on 2023-11-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_updated_at_customuser_updated_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_a',
            new_name='updated_at',
        ),
    ]
