# Generated by Django 4.2.7 on 2023-11-27 21:20

from django.db import migrations, models
# Generated by Django 4.2.7 on 2023-11-27 21:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslistingreview',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='businesslistingsocials',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='businesslistingreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            #field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesslistingreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businesslistingsocials',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            # field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesslistingsocials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='BusinessListingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='BusinessDirectory.businesslisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
        