# Generated by Django 4.2.7 on 2023-11-27 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslistingreview',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='businesslistingsocials',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='businesslistingreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesslistingreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businesslistingsocials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesslistingsocials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
