# Generated by Django 4.2.7 on 2023-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessDirectory', '0002_alter_businesslistingreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businesslistingreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businesslistingsocials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
