# Generated by Django 4.2.7 on 2023-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessDirectory', '0002_alter_businesslistingreview_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesslisting',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='businesslistingrequest',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.AlterField(
            model_name='businesslistingcategory',
            name='image',
            field=models.ImageField(upload_to='business_listing_category_images'),
        ),
        migrations.AlterField(
            model_name='businesslistingimage',
            name='image',
            field=models.ImageField(upload_to='business_listing_images'),
        ),
    ]
