# Generated by Django 4.2.7 on 2023-11-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessDirectory', '0002_alter_businesslistingreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslistingrequest',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='business_listing_request_id_back'),
        ),
        migrations.AlterField(
            model_name='businesslistingrequest',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='business_listing_request_id_front'),
        ),
    ]
